remote_theme: pages-themes/dinky@v0.2.0
github:
  is_project_page: false
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Ling Ho's homepage
# description: Bookmark this to keep an eye on my project updates!